// <auto-generated />
using Eva_Pharma_Task1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eva_Pharma_Task1.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250727190312_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eva_Pharma_Task1.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("catName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("catOrder")
                        .HasColumnType("int");

                    b.Property<bool>("markedAsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            catName = "Category 1",
                            catOrder = 1,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            catName = "Category 2",
                            catOrder = 2,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            catName = "Category 3",
                            catOrder = 3,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            catName = "Category 4",
                            catOrder = 4,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            catName = "Category 5",
                            catOrder = 5,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            catName = "Category 6",
                            catOrder = 6,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            catName = "Category 7",
                            catOrder = 7,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            catName = "Category 8",
                            catOrder = 8,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            catName = "Category 9",
                            catOrder = 9,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            catName = "Category 10",
                            catOrder = 10,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            catName = "Category 11",
                            catOrder = 11,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            catName = "Category 12",
                            catOrder = 12,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            catName = "Category 13",
                            catOrder = 13,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            catName = "Category 14",
                            catOrder = 14,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            catName = "Category 15",
                            catOrder = 15,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 16,
                            catName = "Category 16",
                            catOrder = 16,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 17,
                            catName = "Category 17",
                            catOrder = 17,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 18,
                            catName = "Category 18",
                            catOrder = 18,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 19,
                            catName = "Category 19",
                            catOrder = 19,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 20,
                            catName = "Category 20",
                            catOrder = 20,
                            markedAsDeleted = false
                        });
                });

            modelBuilder.Entity("Eva_Pharma_Task1.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("BookPrice");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author 1",
                            CategoryId = 1,
                            Description = "This is the description of Book 1",
                            Price = 10.0,
                            Title = "Book 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author 2",
                            CategoryId = 2,
                            Description = "This is the description of Book 2",
                            Price = 20.0,
                            Title = "Book 2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author 3",
                            CategoryId = 3,
                            Description = "This is the description of Book 3",
                            Price = 30.0,
                            Title = "Book 3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Author 4",
                            CategoryId = 4,
                            Description = "This is the description of Book 4",
                            Price = 40.0,
                            Title = "Book 4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Author 5",
                            CategoryId = 5,
                            Description = "This is the description of Book 5",
                            Price = 50.0,
                            Title = "Book 5"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Author 6",
                            CategoryId = 6,
                            Description = "This is the description of Book 6",
                            Price = 60.0,
                            Title = "Book 6"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Author 7",
                            CategoryId = 7,
                            Description = "This is the description of Book 7",
                            Price = 70.0,
                            Title = "Book 7"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Author 8",
                            CategoryId = 8,
                            Description = "This is the description of Book 8",
                            Price = 80.0,
                            Title = "Book 8"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Author 9",
                            CategoryId = 9,
                            Description = "This is the description of Book 9",
                            Price = 90.0,
                            Title = "Book 9"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Author 10",
                            CategoryId = 10,
                            Description = "This is the description of Book 10",
                            Price = 100.0,
                            Title = "Book 10"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Author 11",
                            CategoryId = 11,
                            Description = "This is the description of Book 11",
                            Price = 110.0,
                            Title = "Book 11"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Author 12",
                            CategoryId = 12,
                            Description = "This is the description of Book 12",
                            Price = 120.0,
                            Title = "Book 12"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Author 13",
                            CategoryId = 13,
                            Description = "This is the description of Book 13",
                            Price = 130.0,
                            Title = "Book 13"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Author 14",
                            CategoryId = 14,
                            Description = "This is the description of Book 14",
                            Price = 140.0,
                            Title = "Book 14"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Author 15",
                            CategoryId = 15,
                            Description = "This is the description of Book 15",
                            Price = 150.0,
                            Title = "Book 15"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Author 16",
                            CategoryId = 16,
                            Description = "This is the description of Book 16",
                            Price = 160.0,
                            Title = "Book 16"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Author 17",
                            CategoryId = 17,
                            Description = "This is the description of Book 17",
                            Price = 170.0,
                            Title = "Book 17"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Author 18",
                            CategoryId = 18,
                            Description = "This is the description of Book 18",
                            Price = 180.0,
                            Title = "Book 18"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Author 19",
                            CategoryId = 19,
                            Description = "This is the description of Book 19",
                            Price = 190.0,
                            Title = "Book 19"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Author 20",
                            CategoryId = 20,
                            Description = "This is the description of Book 20",
                            Price = 200.0,
                            Title = "Book 20"
                        });
                });

            modelBuilder.Entity("Eva_Pharma_Task1.Models.Product", b =>
                {
                    b.HasOne("Eva_Pharma_Task1.Models.Categories", "category")
                        .WithMany("products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("Eva_Pharma_Task1.Models.Categories", b =>
                {
                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
