// <auto-generated />
using Eva_Pharma_Task1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eva_Pharma_Task1.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eva_Pharma_Task1.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("catName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("catOrder")
                        .HasColumnType("int");

                    b.Property<bool>("markedAsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            catName = "Category 1",
                            catOrder = 1,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            catName = "Category 2",
                            catOrder = 2,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            catName = "Category 3",
                            catOrder = 3,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            catName = "Category 4",
                            catOrder = 4,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            catName = "Category 5",
                            catOrder = 5,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            catName = "Category 6",
                            catOrder = 6,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            catName = "Category 7",
                            catOrder = 7,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            catName = "Category 8",
                            catOrder = 8,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            catName = "Category 9",
                            catOrder = 9,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            catName = "Category 10",
                            catOrder = 10,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            catName = "Category 11",
                            catOrder = 11,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            catName = "Category 12",
                            catOrder = 12,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            catName = "Category 13",
                            catOrder = 13,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            catName = "Category 14",
                            catOrder = 14,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            catName = "Category 15",
                            catOrder = 15,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 16,
                            catName = "Category 16",
                            catOrder = 16,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 17,
                            catName = "Category 17",
                            catOrder = 17,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 18,
                            catName = "Category 18",
                            catOrder = 18,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 19,
                            catName = "Category 19",
                            catOrder = 19,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 20,
                            catName = "Category 20",
                            catOrder = 20,
                            markedAsDeleted = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
